name: Deploy to GitHub Pages

on:
  push:
    branches:
      - main   # Trigger deployment on push to 'main' branch

jobs:
  deploy:
    runs-on: ubuntu-latest  # GitHub Actions runner

    steps:
    - name: Checkout repository
      uses: actions/checkout@v2  # Checks out your repository code

    - name: Setup Node.js
      uses: actions/setup-node@v2
      with:
        node-version: '14'  # Set the Node.js version you need

    - name: Install dependencies
      run: |
        npm install  # If you're using npm (or yarn)

    - name: Build project
      run: |
        npm run build  # Build your project (you can change this if your project uses another build tool)

    - name: Deploy to GitHub Pages
      uses: peaceiris/actions-gh-pages@v3  # Action for deploying to GitHub Pages
      with:
        github_token: ${{ secrets.GITHUB_TOKEN }}  # Automatically uses the token to authenticate
        publish_dir: ./build  # Path to the build directory (adjust as per your project)
